Description: >

  This template deploys a VPC, with a pair of public and private subnets spread 
  across two Availabilty Zones. It deploys an Internet Gateway, with a default 
  route on the public subnets. It deploys a pair of NAT Gateways (one in each
  AZ),  and default routes for them in the private subnets.

  It then deploys a highly available ECS cluster using an AutoScaling Group,
  with ECS hosts distributed across multiple Availability Zones. 

  Last Modified: 22nd September 2016 Author: Paul Maddox <pmaddox@amazon.com>
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://s3.amazonaws.com/cf.yourdomain.com/infrastructure/vpc.yaml?versionid=WH_GYYQbsoadVDXO9Lqv0vhBWzpV0raw
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.180.0.0/16
        PublicSubnet1CIDR: 10.180.8.0/21
        PublicSubnet2CIDR: 10.180.16.0/21
        PublicSubnet3CIDR: 10.180.24.0/21
        PrivateSubnet1CIDR: 10.180.32.0/21
        PrivateSubnet2CIDR: 10.180.40.0/21
        PrivateSubnet3CIDR: 10.180.48.0/21
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://s3.amazonaws.com/cf.yourdomain.com/infrastructure/security-groups.yaml?versionid=BWH8JIRBkP.LggGolE1d6lqUO1_UnQGt
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://s3.amazonaws.com/cf.yourdomain.com/infrastructure/ecs-cluster.yaml?versionid=a7EedtHDRl1jpwm4IWcjdbacOQeBZuUp
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: c5.large
        ClusterSize: 2
        VPC: !GetAtt VPC.Outputs.VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets

